---

- name: "Download github repo and check for changes"
  hosts: localhost
  gather_facts: true
  tasks: 
    - name: "Cloning github"
      git:
        repo: git@github.com:roberto0180/ansible-testing.git
        version: master
        dest: tmp/
        accept_hostkey: yes
      # ssh-agent doesn't allow key to pass through remote sudo commands.
      become: no

- name: "Update F5 configuration"
  hosts: lab
  connection: local
  vars_files:
    - tmp/opt/vars/pools.yaml
    - tmp/opt/vars/nodes.yaml
    - tmp/opt/vars/vips.yaml
    - tmp/opt/vars/clientssl_profiles.yaml

  vars_prompt:
    - name: "username"
      prompt: "Enter BIG-IP username"
      private: yes
    - name: "password"
      prompt: "Enter BIG-IP password"
      private: yes

  vars:
    - ansible_host: localhost
    - ansible_python_interpreter: /Users/roberto.edgar/Downloads/f5-ansible/f5/bin/python
    - provider:
        server: "{{ inventory_hostname }}"
        validate_certs: no
        server_port: 443
        user: "{{ username }}"
        password: "{{ password }}"
    - state: "present"

  tasks:
    - name: Save config, SCF and UCS
      bigip_command:
        provider: "{{ provider }}"
        commands:
          - save /sys config
          - save /sys config file "{{ filename }}".scf no-passphrase
          - save /sys ucs "{{ filename }}".ucs

    - name: Adjust virtual server
      bigip_virtual_server:
        provider: "{{ provider }}"
        name: "{{ item.vs_name }}"
        type: "{{ item.vs_type }}"
        destination: "{{ item.vs_ip }}"
        port: "{{ item.vs_port }}"
        snat: "{{ item.vs_snat }}"
        profiles: "{{ item.vs_profiles | default(omit) }}"
        irules: "{{ item.vs_irules | default(omit) }}"
        state: "{{ item.vs_state }}"
      with_items:
        - "{{ virtuals }}"

    - name: Adjust pools
      bigip_pool:
        provider: "{{ provider }}"
        name: "{{ item.pl_name }}"
        monitors: "{{ item.pl_monitor }}"
        state: "{{ state }}"
      with_items:
        "{{ pools }}"

    - name: Adjust client SSL profiles
      bigip_profile_client_ssl:
        provider: "{{ provider }}"
        name: "{{ item.cssl_pr_name }}"
        ciphers: "{{ item.cssl_pr_ciphers|default(omit) }}"
        parent: "{{ item.cssl_pr_parent_pr }}"
        state: "{{ item.cssl_pr_state}}"
      with_items:
        "{{ clientssl_profiles }}"

    - name: Modify profiles to use inherited ciphers
      bigip_command:
        provider: "{{ provider }}"
        commands:
          - modify ltm profile client-ssl "{{ item.cssl_pr_name }}" ciphers default-value  
      when: item.cssl_pr_ciphers is not defined
      with_items:
        "{{ clientssl_profiles }}"

    - name: Add nodes
      bigip_node:
        provider: "{{ provider }}"
        name: "{{ item.nd_name }}"
        host: "{{ item.nd_address }}"
      with_items:
        "{{ nodes }}"

    - name: Add nodes to pool
      bigip_pool_member:
        provider: "{{ provider }}"
        pool: "{{ item.0.pl_name }}"
        name: "{{ item.1 }}"
        port: "{{ item.0.pl_members_port }}"
        state: "{{ state }}"
      with_subelements:
        - "{{ pools }}"
        - pl_members_node
      when: state == "present"

    - name: Save config
      bigip_command:
        provider: "{{ provider }}"
        commands:
          - save /sys config
